### ISSUE TITLE
Mac OSX Sierra

### ISSUE THREAD

**Issue by tance77** [lucalaissue/riot-api-nodejs#17]
index.ts:188

node_modules/riot-api-nodejs/index.js:188

    constructor(...apiKeys) {
                      ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (riotApi.js:1:77)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)

Getting this error when running on my mac only not on my windows machine.

**Comment by tance77** [comment]
Outdated version of Node.js
